"""Embed the Kinetic design system's fonts as data URIs.

The app has to work offline in a gym and inside a strict-CSP preview, so linking
Google Fonts isn't good enough — a missing display face would flatten the whole
look. This downloads the *latin subset only* and writes fonts.css with the woff2
inlined, which keeps it to a few tens of KB.

Rajdhani and Space Mono are both licensed under the SIL Open Font License, which
permits embedding and redistribution. The licence notice is written into the
generated CSS.

    python tools/fetch_fonts.py
"""

import base64
import os
import re
import urllib.request

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
OUT = os.path.join(ROOT, "fonts.css")

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# family -> weights. Body text deliberately uses the platform UI face instead
# (San Francisco on iOS), which is a better match for a native-feeling app and
# saves ~40 KB.
FAMILIES = [
    ("Rajdhani", [600, 700]),
    ("Space+Mono", [400, 700]),
]


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def latin_faces(family, weights):
    """Return [(weight, woff2_bytes)] for the latin subset only."""
    spec = f"{family}:wght@{';'.join(str(w) for w in weights)}"
    css = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode("utf-8")

    # Blocks are emitted as "/* subset */ @font-face {...}"; keep only /* latin */.
    out = []
    for match in re.finditer(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S):
        subset, body = match.group(1), match.group(2)
        if subset != "latin":
            continue
        weight = int(re.search(r"font-weight:\s*(\d+)", body).group(1))
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
        out.append((weight, fetch(url)))
        print(f"  {family} {weight} latin -> {len(out[-1][1]):,} bytes")
    return out


def main():
    chunks = ["""/* Generated by tools/fetch_fonts.py — do not edit by hand.

   Rajdhani (c) Indian Type Foundry and Space Mono (c) Colophon Foundry are
   licensed under the SIL Open Font License 1.1, which permits embedding.
   Latin subset only. Body copy uses the platform UI font. */
"""]

    for family, weights in FAMILIES:
        name = family.replace("+", " ")
        print(f"{name}:")
        for weight, data in latin_faces(family, weights):
            b64 = base64.b64encode(data).decode("ascii")
            chunks.append(
                "@font-face{"
                f"font-family:'{name}';font-style:normal;font-weight:{weight};font-display:swap;"
                f"src:url(data:font/woff2;base64,{b64}) format('woff2')"
                "}"
            )

    css = "\n".join(chunks) + "\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(css)
    print(f"\nwrote {OUT} ({len(css):,} chars)")


if __name__ == "__main__":
    main()
